### ISSUE TITLE
Feature Request: Establish a GitHub Wiki for Application Documentation

### ISSUE THREAD

**Issue by berntpopp** [halbritter-lab/gene-curator#52]
### Summary
Develop a comprehensive wiki on GitHub to document the usage and features of the gene-curator application. The wiki should be programmatically updatable and editable within the repository.

### Description
As the application grows, the need for detailed and accessible documentation becomes imperative. A GitHub wiki would serve as a centralized source of information for users, developers, and contributors. It should cover usage instructions, feature explanations, development guidelines, and more. The ability to update this documentation programmatically and through repository edits will ensure it remains current and collaborative.

### Acceptance Criteria
- [ ] Set up a GitHub wiki within the gene-curator repository.
- [ ] Create initial pages covering key aspects of the application (e.g., installation, usage, feature guides).
- [ ] Implement a system or a set of guidelines for programmatically updating the wiki.
- [ ] Ensure the wiki is easily editable through the repository to encourage contributions from the community.
- [ ] Document the process for updating the wiki both programmatically and manually.

### User Stories
- As a new user, I want to access clear documentation on how to use the application effectively.
- As a contributor, I need guidelines on how to update and maintain the documentation in line with the project's development.
- As a developer, I want to automate the process of updating the documentation to ensure it stays in sync with the codebase.

### Implementation Details
- Identify the initial set of topics that need to be documented in the wiki.
- Design a template or structure for the wiki pages to maintain consistency.
- Develop scripts or GitHub Actions workflows to automate the updating of certain wiki pages based on codebase changes.
- Write a contributor's guide to document the process for manually updating the wiki.

### Code Snippet
```yml
# Sample GitHub Actions workflow to update the wiki
name: Update Wiki

on:
  push:
    branches:
      - main

jobs:
  update-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Update Wiki
        run: ./scripts/updateWiki.sh
```
